package it.almaviva.difesa.sipad.shared.util;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum StatusEnum {
    CANNOT_FIND_DOCUMENT_TYPE("CANNOT_FIND_DOCUMENT_TYPE"),
    CANNOT_SAVE_DATA("CANNOT_SAVE_DATA"),
    CANNOT_UPDATE_DATA("CANNOT_UPDATE_DATA"),
    CANNOT_DELETE_DATA("CANNOT_DELETE_DATA"),
    ENTITY_NOT_FINDABLE_PARAMETER("ENTITY_NOT_FINDABLE_PARAMETER"),
    GRADE_NOT_FOUND("GRADE_NOT_FOUND"),
    MISSING_EMPLOYEE_ID("MISSING_EMPLOYEE_ID"),
    MISSING_FISCAL_CODE("MISSING_FISCAL_CODE"),
    NO_ROLES_ASSIGNED ("NO_ROLE_ASSIGNED"),
    ROLE_NOT_FOUND ("ROLE_NOT_FOUND"),
    SUBMISSION_DATE_NOT_PRESENT("SUBMISSION_DATE_NOT_PRESENT"),
    SUBMISSION_DATE_SUBSEQUENT_REVOCATION ("SUBMISSION_DATE_SUBSEQUENT_REVOCATION"),
    SURPLUS_BIGGER_SUPERNUMERARY ("SURPLUS_BIGGER_SUPERNUMERARY"),
    USER_NOT_FOUND ("USER_NOT_FOUND");



    private final String nameMessage;
}
